[package]
name = "observatory"
version = "0.1.0"
edition = "2021"

[dependencies]
eframe = "0.31.1"
env_logger = "0.11.6"
dynamical-system = { path = "../dynamical-system" }
tokio = "1.44.0"
dotenvy = "0.15.7"
toml = "0.8.20"
