[package]
name = "llmca"
version = "0.1.0"
edition = "2021"

[dependencies]
dotenv = "0.15.0"
eframe = "0.27.2"
egui = "0.27.2"
egui_graphs = "0.20.0"
itertools = "0.13.0"
macroquad = "0.4.8"
petgraph = "0.6.5"
rand = "0.8.5"
reqwest = { version = "0.12.4", features = ["blocking", "json"] }
serde = "1.0.203"
serde_derive = "1.0.203"
serde_json = "1.0.117"
