[workspace]
members = [
    "dynamical-system",
    "generate-artifacts",
    "minimal-ui",
    "observatory",
    "server",
    "source",
    "swarm",
]
resolver = "2"

# [patch.crates-io]
# log = "0.4.27"
